global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'yess_backend'
    static_configs:
      - targets: ['backend:8000']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']
